package com.manicure.product.mapper;

import com.manicure.product.entity.ServiceComment;
import com.manicure.product.entity.ServiceCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int countByExample(ServiceCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int deleteByExample(ServiceCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int insert(ServiceComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int insertSelective(ServiceComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    List<ServiceComment> selectByExample(ServiceCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    ServiceComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") ServiceComment record, @Param("example") ServiceCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int updateByExample(@Param("record") ServiceComment record, @Param("example") ServiceCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int updateByPrimaryKeySelective(ServiceComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_comment
     *
     * @mbggenerated Wed Jul 22 20:39:19 CST 2015
     */
    int updateByPrimaryKey(ServiceComment record);
}