package com.manicure.keystone.entity;

public class WeatherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.id
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.city
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.weather
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    private String weather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.a space clo
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    private String aSpaceClo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weatherinfo.id
     *
     * @return the value of weatherinfo.id
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weatherinfo.id
     *
     * @param id the value for weatherinfo.id
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weatherinfo.city
     *
     * @return the value of weatherinfo.city
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weatherinfo.city
     *
     * @param city the value for weatherinfo.city
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weatherinfo.weather
     *
     * @return the value of weatherinfo.weather
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weatherinfo.weather
     *
     * @param weather the value for weatherinfo.weather
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weatherinfo.a space clo
     *
     * @return the value of weatherinfo.a space clo
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public String getaSpaceClo() {
        return aSpaceClo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weatherinfo.a space clo
     *
     * @param aSpaceClo the value for weatherinfo.a space clo
     *
     * @mbggenerated Sun Jul 19 04:37:20 CST 2015
     */
    public void setaSpaceClo(String aSpaceClo) {
        this.aSpaceClo = aSpaceClo == null ? null : aSpaceClo.trim();
    }
}