package com.manicure.technician.mapper;

import com.manicure.technician.entity.Technician;
import com.manicure.technician.entity.TechnicianExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TechnicianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int countByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int deleteByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int insert(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int insertSelective(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    List<Technician> selectByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    Technician selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") Technician record, @Param("example") TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int updateByExample(@Param("record") Technician record, @Param("example") TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int updateByPrimaryKeySelective(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technician
     *
     * @mbggenerated Wed Jul 22 21:29:50 CST 2015
     */
    int updateByPrimaryKey(Technician record);
}