package com.manicure.product.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderidIsNull() {
			addCriterion("orderid is null");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNotNull() {
			addCriterion("orderid is not null");
			return (Criteria) this;
		}

		public Criteria andOrderidEqualTo(Integer value) {
			addCriterion("orderid =", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotEqualTo(Integer value) {
			addCriterion("orderid <>", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThan(Integer value) {
			addCriterion("orderid >", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderid >=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThan(Integer value) {
			addCriterion("orderid <", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThanOrEqualTo(Integer value) {
			addCriterion("orderid <=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidIn(List<Integer> values) {
			addCriterion("orderid in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotIn(List<Integer> values) {
			addCriterion("orderid not in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidBetween(Integer value1, Integer value2) {
			addCriterion("orderid between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
			addCriterion("orderid not between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andServiceidIsNull() {
			addCriterion("serviceid is null");
			return (Criteria) this;
		}

		public Criteria andServiceidIsNotNull() {
			addCriterion("serviceid is not null");
			return (Criteria) this;
		}

		public Criteria andServiceidEqualTo(Integer value) {
			addCriterion("serviceid =", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotEqualTo(Integer value) {
			addCriterion("serviceid <>", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThan(Integer value) {
			addCriterion("serviceid >", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("serviceid >=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThan(Integer value) {
			addCriterion("serviceid <", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThanOrEqualTo(Integer value) {
			addCriterion("serviceid <=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidIn(List<Integer> values) {
			addCriterion("serviceid in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotIn(List<Integer> values) {
			addCriterion("serviceid not in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidBetween(Integer value1, Integer value2) {
			addCriterion("serviceid between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotBetween(Integer value1, Integer value2) {
			addCriterion("serviceid not between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("`time` is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("`time` is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("`time` =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("`time` <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("`time` >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("`time` >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("`time` <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("`time` <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("`time` in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("`time` not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("`time` between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("`time` not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andStoreidIsNull() {
			addCriterion("storeid is null");
			return (Criteria) this;
		}

		public Criteria andStoreidIsNotNull() {
			addCriterion("storeid is not null");
			return (Criteria) this;
		}

		public Criteria andStoreidEqualTo(Integer value) {
			addCriterion("storeid =", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidNotEqualTo(Integer value) {
			addCriterion("storeid <>", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidGreaterThan(Integer value) {
			addCriterion("storeid >", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
			addCriterion("storeid >=", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidLessThan(Integer value) {
			addCriterion("storeid <", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidLessThanOrEqualTo(Integer value) {
			addCriterion("storeid <=", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidIn(List<Integer> values) {
			addCriterion("storeid in", values, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidNotIn(List<Integer> values) {
			addCriterion("storeid not in", values, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidBetween(Integer value1, Integer value2) {
			addCriterion("storeid between", value1, value2, "storeid");
			return (Criteria) this;
		}

		public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
			addCriterion("storeid not between", value1, value2, "storeid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidIsNull() {
			addCriterion("technicianid is null");
			return (Criteria) this;
		}

		public Criteria andTechnicianidIsNotNull() {
			addCriterion("technicianid is not null");
			return (Criteria) this;
		}

		public Criteria andTechnicianidEqualTo(Integer value) {
			addCriterion("technicianid =", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidNotEqualTo(Integer value) {
			addCriterion("technicianid <>", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidGreaterThan(Integer value) {
			addCriterion("technicianid >", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidGreaterThanOrEqualTo(Integer value) {
			addCriterion("technicianid >=", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidLessThan(Integer value) {
			addCriterion("technicianid <", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidLessThanOrEqualTo(Integer value) {
			addCriterion("technicianid <=", value, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidIn(List<Integer> values) {
			addCriterion("technicianid in", values, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidNotIn(List<Integer> values) {
			addCriterion("technicianid not in", values, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidBetween(Integer value1, Integer value2) {
			addCriterion("technicianid between", value1, value2, "technicianid");
			return (Criteria) this;
		}

		public Criteria andTechnicianidNotBetween(Integer value1, Integer value2) {
			addCriterion("technicianid not between", value1, value2,
					"technicianid");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(BigDecimal value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(BigDecimal value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(BigDecimal value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(BigDecimal value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<BigDecimal> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<BigDecimal> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andActpriceIsNull() {
			addCriterion("actprice is null");
			return (Criteria) this;
		}

		public Criteria andActpriceIsNotNull() {
			addCriterion("actprice is not null");
			return (Criteria) this;
		}

		public Criteria andActpriceEqualTo(BigDecimal value) {
			addCriterion("actprice =", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceNotEqualTo(BigDecimal value) {
			addCriterion("actprice <>", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceGreaterThan(BigDecimal value) {
			addCriterion("actprice >", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("actprice >=", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceLessThan(BigDecimal value) {
			addCriterion("actprice <", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("actprice <=", value, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceIn(List<BigDecimal> values) {
			addCriterion("actprice in", values, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceNotIn(List<BigDecimal> values) {
			addCriterion("actprice not in", values, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("actprice between", value1, value2, "actprice");
			return (Criteria) this;
		}

		public Criteria andActpriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("actprice not between", value1, value2, "actprice");
			return (Criteria) this;
		}

		public Criteria andTicketidIsNull() {
			addCriterion("ticketid is null");
			return (Criteria) this;
		}

		public Criteria andTicketidIsNotNull() {
			addCriterion("ticketid is not null");
			return (Criteria) this;
		}

		public Criteria andTicketidEqualTo(Integer value) {
			addCriterion("ticketid =", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotEqualTo(Integer value) {
			addCriterion("ticketid <>", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidGreaterThan(Integer value) {
			addCriterion("ticketid >", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidGreaterThanOrEqualTo(Integer value) {
			addCriterion("ticketid >=", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidLessThan(Integer value) {
			addCriterion("ticketid <", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidLessThanOrEqualTo(Integer value) {
			addCriterion("ticketid <=", value, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidIn(List<Integer> values) {
			addCriterion("ticketid in", values, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotIn(List<Integer> values) {
			addCriterion("ticketid not in", values, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidBetween(Integer value1, Integer value2) {
			addCriterion("ticketid between", value1, value2, "ticketid");
			return (Criteria) this;
		}

		public Criteria andTicketidNotBetween(Integer value1, Integer value2) {
			addCriterion("ticketid not between", value1, value2, "ticketid");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("`state` is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("`state` is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("`state` =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("`state` <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("`state` >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("`state` >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("`state` <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("`state` <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("`state` in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("`state` not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("`state` between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("`state` not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 19 21:37:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}