package com.manicure.product.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.serviceid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer serviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.time
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.storeid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer storeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.technicianid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer technicianid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.price
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.actprice
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private BigDecimal actprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.ticketid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer ticketid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.userid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.state
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderid
	 * @return  the value of order.orderid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderid
	 * @param orderid  the value for order.orderid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.serviceid
	 * @return  the value of order.serviceid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getServiceid() {
		return serviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.serviceid
	 * @param serviceid  the value for order.serviceid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.time
	 * @return  the value of order.time
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.time
	 * @param time  the value for order.time
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.storeid
	 * @return  the value of order.storeid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getStoreid() {
		return storeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.storeid
	 * @param storeid  the value for order.storeid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setStoreid(Integer storeid) {
		this.storeid = storeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.technicianid
	 * @return  the value of order.technicianid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getTechnicianid() {
		return technicianid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.technicianid
	 * @param technicianid  the value for order.technicianid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setTechnicianid(Integer technicianid) {
		this.technicianid = technicianid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.price
	 * @return  the value of order.price
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.price
	 * @param price  the value for order.price
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.actprice
	 * @return  the value of order.actprice
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public BigDecimal getActprice() {
		return actprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.actprice
	 * @param actprice  the value for order.actprice
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setActprice(BigDecimal actprice) {
		this.actprice = actprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.ticketid
	 * @return  the value of order.ticketid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getTicketid() {
		return ticketid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.ticketid
	 * @param ticketid  the value for order.ticketid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setTicketid(Integer ticketid) {
		this.ticketid = ticketid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.userid
	 * @return  the value of order.userid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.userid
	 * @param userid  the value for order.userid
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.state
	 * @return  the value of order.state
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.state
	 * @param state  the value for order.state
	 * @mbggenerated  Mon Jul 20 20:27:17 CST 2015
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}