package com.manicure.product.entity;

import java.math.BigDecimal;

public class Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.serviceid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.name
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.description
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.sales
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Long sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.price
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.taketime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Integer taketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.keeptime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Integer keeptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.type
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.imageid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    private Integer imageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.serviceid
     *
     * @return the value of service.serviceid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.serviceid
     *
     * @param serviceid the value for service.serviceid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.name
     *
     * @return the value of service.name
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.name
     *
     * @param name the value for service.name
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.description
     *
     * @return the value of service.description
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.description
     *
     * @param description the value for service.description
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.sales
     *
     * @return the value of service.sales
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Long getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.sales
     *
     * @param sales the value for service.sales
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setSales(Long sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.price
     *
     * @return the value of service.price
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.price
     *
     * @param price the value for service.price
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.taketime
     *
     * @return the value of service.taketime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Integer getTaketime() {
        return taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.taketime
     *
     * @param taketime the value for service.taketime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setTaketime(Integer taketime) {
        this.taketime = taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.keeptime
     *
     * @return the value of service.keeptime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Integer getKeeptime() {
        return keeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.keeptime
     *
     * @param keeptime the value for service.keeptime
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setKeeptime(Integer keeptime) {
        this.keeptime = keeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.type
     *
     * @return the value of service.type
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.type
     *
     * @param type the value for service.type
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.imageid
     *
     * @return the value of service.imageid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public Integer getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.imageid
     *
     * @param imageid the value for service.imageid
     *
     * @mbggenerated Sun Jul 19 21:37:38 CST 2015
     */
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }
}