package com.manicure.product.entity;

public class ServiceType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_type.typeid
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	private Integer typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_type.name
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_type.description
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_type.typeid
	 * @return  the value of service_type.typeid
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_type.typeid
	 * @param typeid  the value for service_type.typeid
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_type.name
	 * @return  the value of service_type.name
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_type.name
	 * @param name  the value for service_type.name
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_type.description
	 * @return  the value of service_type.description
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_type.description
	 * @param description  the value for service_type.description
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}