package com.manicure.product.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ServiceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public ServiceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServiceidIsNull() {
			addCriterion("serviceid is null");
			return (Criteria) this;
		}

		public Criteria andServiceidIsNotNull() {
			addCriterion("serviceid is not null");
			return (Criteria) this;
		}

		public Criteria andServiceidEqualTo(Integer value) {
			addCriterion("serviceid =", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotEqualTo(Integer value) {
			addCriterion("serviceid <>", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThan(Integer value) {
			addCriterion("serviceid >", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("serviceid >=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThan(Integer value) {
			addCriterion("serviceid <", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThanOrEqualTo(Integer value) {
			addCriterion("serviceid <=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidIn(List<Integer> values) {
			addCriterion("serviceid in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotIn(List<Integer> values) {
			addCriterion("serviceid not in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidBetween(Integer value1, Integer value2) {
			addCriterion("serviceid between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotBetween(Integer value1, Integer value2) {
			addCriterion("serviceid not between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("`name` is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("`name` is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("`name` =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("`name` <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("`name` >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("`name` >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("`name` <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("`name` <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("`name` like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("`name` not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("`name` in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("`name` not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("`name` between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("`name` not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andSalesIsNull() {
			addCriterion("sales is null");
			return (Criteria) this;
		}

		public Criteria andSalesIsNotNull() {
			addCriterion("sales is not null");
			return (Criteria) this;
		}

		public Criteria andSalesEqualTo(Long value) {
			addCriterion("sales =", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotEqualTo(Long value) {
			addCriterion("sales <>", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThan(Long value) {
			addCriterion("sales >", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThanOrEqualTo(Long value) {
			addCriterion("sales >=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThan(Long value) {
			addCriterion("sales <", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThanOrEqualTo(Long value) {
			addCriterion("sales <=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesIn(List<Long> values) {
			addCriterion("sales in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotIn(List<Long> values) {
			addCriterion("sales not in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesBetween(Long value1, Long value2) {
			addCriterion("sales between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotBetween(Long value1, Long value2) {
			addCriterion("sales not between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(BigDecimal value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(BigDecimal value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(BigDecimal value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(BigDecimal value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<BigDecimal> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<BigDecimal> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andTaketimeIsNull() {
			addCriterion("taketime is null");
			return (Criteria) this;
		}

		public Criteria andTaketimeIsNotNull() {
			addCriterion("taketime is not null");
			return (Criteria) this;
		}

		public Criteria andTaketimeEqualTo(Integer value) {
			addCriterion("taketime =", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeNotEqualTo(Integer value) {
			addCriterion("taketime <>", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeGreaterThan(Integer value) {
			addCriterion("taketime >", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("taketime >=", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeLessThan(Integer value) {
			addCriterion("taketime <", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeLessThanOrEqualTo(Integer value) {
			addCriterion("taketime <=", value, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeIn(List<Integer> values) {
			addCriterion("taketime in", values, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeNotIn(List<Integer> values) {
			addCriterion("taketime not in", values, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeBetween(Integer value1, Integer value2) {
			addCriterion("taketime between", value1, value2, "taketime");
			return (Criteria) this;
		}

		public Criteria andTaketimeNotBetween(Integer value1, Integer value2) {
			addCriterion("taketime not between", value1, value2, "taketime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeIsNull() {
			addCriterion("keeptime is null");
			return (Criteria) this;
		}

		public Criteria andKeeptimeIsNotNull() {
			addCriterion("keeptime is not null");
			return (Criteria) this;
		}

		public Criteria andKeeptimeEqualTo(Integer value) {
			addCriterion("keeptime =", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeNotEqualTo(Integer value) {
			addCriterion("keeptime <>", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeGreaterThan(Integer value) {
			addCriterion("keeptime >", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("keeptime >=", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeLessThan(Integer value) {
			addCriterion("keeptime <", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeLessThanOrEqualTo(Integer value) {
			addCriterion("keeptime <=", value, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeIn(List<Integer> values) {
			addCriterion("keeptime in", values, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeNotIn(List<Integer> values) {
			addCriterion("keeptime not in", values, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeBetween(Integer value1, Integer value2) {
			addCriterion("keeptime between", value1, value2, "keeptime");
			return (Criteria) this;
		}

		public Criteria andKeeptimeNotBetween(Integer value1, Integer value2) {
			addCriterion("keeptime not between", value1, value2, "keeptime");
			return (Criteria) this;
		}

		public Criteria andServicetypeIsNull() {
			addCriterion("servicetype is null");
			return (Criteria) this;
		}

		public Criteria andServicetypeIsNotNull() {
			addCriterion("servicetype is not null");
			return (Criteria) this;
		}

		public Criteria andServicetypeEqualTo(Integer value) {
			addCriterion("servicetype =", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeNotEqualTo(Integer value) {
			addCriterion("servicetype <>", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeGreaterThan(Integer value) {
			addCriterion("servicetype >", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("servicetype >=", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeLessThan(Integer value) {
			addCriterion("servicetype <", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeLessThanOrEqualTo(Integer value) {
			addCriterion("servicetype <=", value, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeIn(List<Integer> values) {
			addCriterion("servicetype in", values, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeNotIn(List<Integer> values) {
			addCriterion("servicetype not in", values, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeBetween(Integer value1, Integer value2) {
			addCriterion("servicetype between", value1, value2, "servicetype");
			return (Criteria) this;
		}

		public Criteria andServicetypeNotBetween(Integer value1, Integer value2) {
			addCriterion("servicetype not between", value1, value2,
					"servicetype");
			return (Criteria) this;
		}

		public Criteria andImageidIsNull() {
			addCriterion("imageid is null");
			return (Criteria) this;
		}

		public Criteria andImageidIsNotNull() {
			addCriterion("imageid is not null");
			return (Criteria) this;
		}

		public Criteria andImageidEqualTo(Integer value) {
			addCriterion("imageid =", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotEqualTo(Integer value) {
			addCriterion("imageid <>", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidGreaterThan(Integer value) {
			addCriterion("imageid >", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidGreaterThanOrEqualTo(Integer value) {
			addCriterion("imageid >=", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidLessThan(Integer value) {
			addCriterion("imageid <", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidLessThanOrEqualTo(Integer value) {
			addCriterion("imageid <=", value, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidIn(List<Integer> values) {
			addCriterion("imageid in", values, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotIn(List<Integer> values) {
			addCriterion("imageid not in", values, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidBetween(Integer value1, Integer value2) {
			addCriterion("imageid between", value1, value2, "imageid");
			return (Criteria) this;
		}

		public Criteria andImageidNotBetween(Integer value1, Integer value2) {
			addCriterion("imageid not between", value1, value2, "imageid");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNull() {
			addCriterion("ordertype is null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNotNull() {
			addCriterion("ordertype is not null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeEqualTo(Integer value) {
			addCriterion("ordertype =", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotEqualTo(Integer value) {
			addCriterion("ordertype <>", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThan(Integer value) {
			addCriterion("ordertype >", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ordertype >=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThan(Integer value) {
			addCriterion("ordertype <", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThanOrEqualTo(Integer value) {
			addCriterion("ordertype <=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIn(List<Integer> values) {
			addCriterion("ordertype in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotIn(List<Integer> values) {
			addCriterion("ordertype not in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeBetween(Integer value1, Integer value2) {
			addCriterion("ordertype between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotBetween(Integer value1, Integer value2) {
			addCriterion("ordertype not between", value1, value2, "ordertype");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service
	 * @mbggenerated  Wed Jul 22 20:39:19 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 19 21:37:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}